version: "3.8"
services:
  hadoop-namenode-bda:
    image: bde2020/hadoop-namenode:latest
    container_name: hadoop-namenode-bda
    ports:
      - "9870:9870"  # Web UI
      - "9000:9000"  # NameNode RPC
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-bda:9000
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - bda_network

  hadoop-datanode-bda:
    image: bde2020/hadoop-datanode:latest
    container_name: hadoop-datanode-bda
    depends_on:
      - hadoop-namenode-bda
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-bda:9000
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - bda_network

  spark-master-bda:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master-bda
    ports:
      - "8082:8082"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master-bda
    networks:
      - bda_network

  spark-worker-bda1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-bda1
    depends_on:
      - spark-master-bda
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-bda:7077
      - SPARK_MASTER=spark://spark-master-bda:7077
    networks:
      - bda_network

volumes:
  namenode_data:
  datanode_data:

networks:
  bda_network:
    driver: bridge
    name: bda_network