version: "3.8"

services:
  hbasebda:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbasebda
    volumes:
      - hbase_data:/hbase-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
    environment:
      - HADOOP_USER_NAME=hbase
      - HBASE_CONF_hbase_cluster_distributed=true
      - HBASE_CONF_hbase_zookeeper_property_clientPort=2181
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeperbda
      - HBASE_CONF_hbase_zookeeper_znode_parent=/hbase
      - HBASE_CONF_hbase_rootdir=hdfs://hadoop-namenode-bda:9000/hbase
    networks:
      - bda_network

volumes:
  hbase_data:

networks:
  bda_network:
    driver: bridge
    name: bda_network
