version: "3.8"
services:
  custom_airflow:
    image: aq1bdocker/custom-airflow
    container_name: custom_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db
    volumes:
      - ./custom_airflow/dags:/usr/local/airflow/dags
      - ./custom_airflow/logs:/usr/local/airflow/logs
      - ./custom_airflow/plugins:/usr/local/airflow/plugins
      - ./custom_airflow/hdfs:/usr/local/airflow/hdfs  # Persist HDFS changes
      - ./custom_airflow/hbase:/usr/local/airflow/hbase  # Persist HBase configurations
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker CLI access
    ports:
      - "8090:8080"  # Avoid conflict with the existing Airflow setup
    networks:
      - bda_network
    command: ["webserver"]

networks:
  bda_network:
    driver: bridge
    name: bda_network
